version: '3.8'

services:
  backend:
    # 이 이미지는 GitHub Actions에서 빌드하여 GHCR에 푸시할 이미지입니다.
    # ${{ GITHUB_REPOSITORY }} 와 같은 변수는 Actions 워크플로우에서 동적으로 채워집니다.
    image: ghcr.io/${{ GITHUB_REPOSITORY }}/chatbot-backend:latest
    
    container_name: chatbot_backend
    restart: always
    env_file:
      # 서버의 /home/jober/Final-1team-AI/.env 파일을 사용하도록 경로를 지정합니다.
      - /home/jober/Final-1team-AI/.env
    ports:
      - "8000:8000"