# /docker-compose.yml (프로젝트 최상위 경로)

version: '3.11.9'

services:
  backend:
    # [수정] 이 이미지는 GitHub Actions에서 빌드하여 GHCR에 푸시할 이미지입니다.
    # 'GITHUB_REPOSITORY_PLACEHOLDER'는 Actions 워크플로우에서 동적으로 채워집니다.
    image: ghcr.io/GITHUB_REPOSITORY_PLACEHOLDER/chatbot-backend:latest
    
    container_name: chatbot_backend
    restart: always
    env_file:
      # 서버의 /home/jober/Final-1team-AI/.env 파일을 사용하도록 경로를 지정합니다.
      - /home/jober/Final-1team-AI/.env
    ports:
      - "8000:8000"